### ISSUE TITLE
Nats Jwt Authentication

### ISSUE THREAD

**Issue by Zetanova** [LuxChanLu/n8n-nodes-nats#1]
beside user/pass and token authentication, nats supports its own mechanism.
https://docs.nats.io/running-a-nats-service/configuration/securing_nats/auth_intro/jwt

A separate fields for jwt value and nkey value are required.

```ts
const nats = connect({
        servers: natsConfig.servers,
        authenticator: jwtAuthenticator(natsConfig.jwt, natsConfig.nkey),
        tls: {
            caFile: natsConfig.caPath
        },
        debug: natsConfig.debug
    })
```

I have time I will try it in an fork and make a PR,
but will most likely be faster if the maintainer find 5min for it.

**Comment by Hugome** [comment]
Authentificators added in v1.1.1 :+1:
(https://github.com/LuxChanLu/n8n-nodes-nats/blob/master/nodes/Nats/common.ts)

**Comment by Zetanova** [comment]
I tested now it out, without a success

When I open the "nats cedentials" 
in the n8n consolse following error is printed out:
`Error: Node not found: @luxchanlu/n8n-nodes-nats.@luxchanlu/n8n-nodes-nats.nats`

following fields are set:
Name: named|empty
Server: nats://nats.h15007.svc:4222
TLS CA Cert:  [the ca chain pem text]
JwtSeed: [the nkey]
JwtToken: [the jwt]
Debug: false|true

On save of the credential it wents to "Saving" without any change.

On credential dialog open and **save** n8n makes a http request 
POST https://n8n/rest/credentials/test

With the same error as in the console
```
{
    "code": 0,
    "message": "Node not found: @luxchanlu/n8n-nodes-nats.@luxchanlu/n8n-nodes-nats.nats"
}
```

All settings/fields are saved but only the "TLS CA Cert" is empty.
"tls.ca" is not listed in the data of the save http "PATCH" command,
this explains the empty field. 

I think the dot in the creds setting field name is not allowed
Maybe the "Error: Node not found: @luxchanlu/n8n-nodes-nats.@luxchanlu/n8n-nodes-nats.nats" error is related to it.

**Comment by Zetanova** [comment]
@Hugome And thanks for the fast update

**Comment by Hugome** [comment]
I think you right the "." is not really liked, I just changed it to "tlsCa"/"tlsCert"/"tlsKey", you can try with the v1.1.2 :)

**Comment by Zetanova** [comment]
thanks, it works !!!

Some other notes:
1) after the update I needed to clear the browser cache or else it still used the old field names.
2) For the ca cert pem field the "Open editor window" function need to be used or else the newlines are getting removed. 
New Lines are required in the pem text.
3) The certificate n8n test request on open and save still fails. Seams to be an other issue.

**Comment by Zetanova** [comment]
The publishing to nats works fine

I tried now the jetstream trigger and it fails with
```
Error: unable to get local issuer certificate
    at TLSSocket.onConnectSecure (node:_tls_wrap:1600:34)
    at TLSSocket.emit (node:events:517:28)
    at TLSSocket.emit (node:domain:552:15)
    at TLSSocket._finishInit (node:_tls_wrap:1017:8)
    at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:803:12)
    at TLSWrap.callbackTrampoline (node:internal/async_hooks:130:17)
```

It seams that the js node does not use the new factory function:
https://github.com/LuxChanLu/n8n-nodes-nats/blob/master/nodes/JetStream/common.ts

Beside this the nats connection instance can/should be a singleton for each credentials. 
Don't know how well it is inline with n8n system. It can be viewed as a recommendation.

**Comment by Zetanova** [comment]
I made a bit of research into n8n resource management like for a singleton connection instance.
There is currently any, mention my idea here. 
https://community.n8n.io/t/reuse-database-connections/15687/10?u=zetanova

Doesn't really matter much for the nats node.

**Comment by Zetanova** [comment]
this https://github.com/LuxChanLu/n8n-nodes-nats/pull/2 fixes the jwt auth for jetstream trigger.
